### ISSUE TITLE
Look through old Debian bug reports

### ISSUE THREAD

**Issue by mgedmin** [gtimelog/gtimelog#3]
When the gtimelog package was [dropped](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=585145#95) from Debian, all the old bug reports got closed.  We should review them to see if any need to be reopened/forwarded upstream.

These are the bugs:
- [x] [492988](http://bugs.debian.org/492988): Add support for a new style of weekly summary -- ~~LP #638245~~ [LP #638242](http://pad.lv/638242)
- [x] [502324](http://bugs.debian.org/502324): Add ability to hide time label in tray icon -- [LP #638245](http://pad.lv/638245)
- [x] [512471](http://bugs.debian.org/512471): misses external dependencies (gvim, oocalc, mutt), very similar to Ubuntu bug [LP #221362](http://pad.lv/221362)
- [x] [520516](http://bugs.debian.org/520516): confusion about "A" versus "A: x" **not forwarded upstream**
- [x] [560981](http://bugs.debian.org/560981): egg.trayicon is deprecated, use gtk.StatusIcon instead (fixed in gtimelog 0.3.1)
- [x] [572017](http://bugs.debian.org/572017): new upstream version available: 0.3.1
- [x] [581938](http://bugs.debian.org/581938): double-click on a category does not give the focus to the text field anymore -- [LP #608734](http://pad.lv/608734), fixed in 0.3.2
- [x] [592424](http://bugs.debian.org/592424): can't generate reports [LP #328618](http://pad.lv/328618), duplicate of [LP #221362](http://pad.lv/221362)
- [x] [595280](http://bugs.debian.org/595280): generic name in .desktop file, fixed in gtimelog 0.4.0
- [x] [585145](http://bugs.debian.org/585145): request for adoption by Simon McVittie; an interesting historical discussion
- [x] [591078](http://bugs.debian.org/591078): intent to adopt by Chris Silva in 2010 (who changed his mind later, in bug 585145).

I'll check them off after reviewing.
